name: Render README

on: [pull_request]

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
              ref: ${{ github.ref }}
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages("remotes")
          remotes::install_local(".")
          remotes::install_cran("rmarkdown")
          remotes::install_cran("magrittr")
          remotes::install_cran("dplyr")
          remotes::install_cran("ggplot2")
          remotes::install_cran("vdiffr")
          remotes::install_cran("data.table")
          remotes::install_cran("covr")
          remotes::install_github("lorenzwalthert/gitsum")
          remotes::install_github("pharmaR/riskmetric@v0.1.1")
          install.packages("ggthemes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Render README
        run: |
          Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Commit results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          gh pr checkout ${{ github.event.pull_request.number }}
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push || echo "No changes to commit"
